/**
 * Datos de la plantilla inicial de FAT Burger (sección 18 de la
 * especificación) - separado de seed.js para que src/scoring/validar.js
 * pueda reusar exactamente los mismos datos sin tocar la base.
 */

const SECTORES = [
  { nombre: 'Local Exterior', peso: 0.15 },
  { nombre: 'Local Interior Atención', peso: 0.25 },
  { nombre: 'Administración', peso: 0.05 },
  { nombre: 'Cocina', peso: 0.45 },
  { nombre: 'Depósito/Almacenamiento', peso: 0.1 },
];

const AREAS = [
  { nombre: 'Infraestructura', peso: 0.1 },
  { nombre: 'Limpieza', peso: 0.15 },
  { nombre: 'Marca', peso: 0.2 },
  { nombre: 'Atención / Operación', peso: 0.15 },
  { nombre: 'Bromatología', peso: 0.3 },
  { nombre: 'Documentación / Legales', peso: 0.1 },
];

// [sector, area, texto, peso, critico, informeInSitu] - tal cual la seccion
// 18.1 de la especificacion (100 items).
const ITEMS = [
  ['Local Exterior', 'Infraestructura', 'Cartel exterior en condiciones', 2, false, false],
  ['Local Exterior', 'Infraestructura', 'Fachada en buen estado', 1, false, false],
  ['Local Exterior', 'Infraestructura', 'Área de ingreso peatonal limpia y segura', 1, false, false],
  ['Local Exterior', 'Infraestructura', 'Puerta de ingreso en buen estado', 1, false, false],
  ['Local Exterior', 'Infraestructura', 'Luminaria exterior funcional', 1, false, false],
  ['Local Exterior', 'Infraestructura', 'Vidrios sin roturas', 3, false, false],
  ['Local Exterior', 'Limpieza', 'Limpieza exterior general', 2, false, false],
  ['Local Exterior', 'Limpieza', 'Limpieza de puerta de ingreso', 1, false, false],
  ['Local Exterior', 'Limpieza', 'Limpieza de vidrios', 1, false, true],
  ['Local Exterior', 'Marca', 'Presencia de objetos ajenos a la marca no autorizados en fachada', 3, false, true],
  ['Local Interior Atención', 'Infraestructura', 'Mostrador en condiciones', 2, false, false],
  ['Local Interior Atención', 'Infraestructura', 'Paredes, pisos y aberturas', 2, false, false],
  ['Local Interior Atención', 'Infraestructura', 'Vidrios sin roturas interior', 3, false, false],
  ['Local Interior Atención', 'Infraestructura', 'Climatización funcional', 1, false, false],
  ['Local Interior Atención', 'Infraestructura', 'Cartelería de señalización presente', 2, false, false],
  ['Local Interior Atención', 'Infraestructura', 'Heladera de bebidas', 2, false, false],
  ['Local Interior Atención', 'Limpieza', 'Limpieza general interior', 2, false, false],
  ['Local Interior Atención', 'Limpieza', 'Limpieza de baños del personal', 3, false, true],
  ['Local Interior Atención', 'Limpieza', 'Frecuencia de retiro de residuos', 2, false, false],
  ['Local Interior Atención', 'Limpieza', 'Heladera de bebidas', 2, false, false],
  ['Local Interior Atención', 'Limpieza', 'Baños de clientes en condiciones', 3, false, true],
  ['Local Interior Atención', 'Marca', 'Material gráfico actualizado', 2, false, false],
  ['Local Interior Atención', 'Marca', 'Carta actualizada visible', 3, false, true],
  ['Local Interior Atención', 'Marca', 'Bebidas exhibidas correctas', 1, false, false],
  ['Local Interior Atención', 'Marca', 'Personal con uniforme completo', 2, false, false],
  ['Local Interior Atención', 'Marca', 'Presencia de objetos ajenos a la marca no autorizados en mostrador', 3, false, true],
  ['Local Interior Atención', 'Marca', 'Funcionan correctamente todos los medios de pago', 1, false, false],
  ['Local Interior Atención', 'Atención / Operación', 'Amabilidad y cordialidad del personal hacia los clientes', 1, false, false],
  ['Local Interior Atención', 'Atención / Operación', 'Conocimiento de la carta', 2, false, false],
  ['Local Interior Atención', 'Atención / Operación', 'Conocimiento de promociones', 2, false, false],
  ['Local Interior Atención', 'Atención / Operación', 'Correcto lineamiento de marca para la toma de pedidos', 2, false, false],
  ['Local Interior Atención', 'Atención / Operación', 'Uso correcto de los atajos de Whatsapp para la toma de pedidos', 3, false, false],
  ['Local Interior Atención', 'Atención / Operación', 'Control de pedido en carga y entrega', 2, false, false],
  ['Local Interior Atención', 'Atención / Operación', 'Limpieza y rotación de mesas', 3, false, true],
  ['Local Interior Atención', 'Atención / Operación', 'Correcto manejo del flujo de delivery', 2, false, false],
  ['Local Interior Atención', 'Bromatología', 'Cuentan con cofias descartables para ingresar al sector de cocina', 3, false, true],
  ['Local Interior Atención', 'Bromatología', 'El personal presenta correcta condiciones de higiene', 3, false, false],
  ['Administración', 'Marca', 'Cantidad mínima de staff exigido', 3, false, false],
  ['Administración', 'Documentación / Legales', 'Habilitación vigente', 3, true, true],
  ['Administración', 'Documentación / Legales', 'Libro de actas firmado por DT', 3, false, true],
  ['Administración', 'Documentación / Legales', 'Carnet de manipulación vigente', 3, false, false],
  ['Administración', 'Documentación / Legales', 'Certificado de desinfección', 3, false, false],
  ['Administración', 'Documentación / Legales', 'Certificado de limpieza de campana y ductos', 2, false, false],
  ['Administración', 'Documentación / Legales', 'Matafuegos en fecha y en correcto funcionamiento', 3, false, false],
  ['Administración', 'Documentación / Legales', 'Empleados asegurados', 3, false, false],
  ['Administración', 'Documentación / Legales', 'Botiquín completo y visible', 3, false, false],
  ['Administración', 'Documentación / Legales', 'Servicio de emergencia del local contratado y al día', 3, false, false],
  ['Administración', 'Documentación / Legales', 'Número de contacto de servicio de emergencia visible y de conocimiento de todos los empleados', 1, false, false],
  ['Administración', 'Documentación / Legales', 'Servicio de retiro de residuos contratado', 2, false, false],
  ['Cocina', 'Infraestructura', 'Equipos de frío suficientes y funcionando', 3, false, false],
  ['Cocina', 'Infraestructura', 'Rejillas con trampa anti insectos', 3, false, false],
  ['Cocina', 'Infraestructura', 'Burletes de heladeras en condiciones', 2, false, false],
  ['Cocina', 'Infraestructura', 'Plancha sin fisuras ni óxido ni deformaciones. Con bandeja de drenaje', 3, false, false],
  ['Cocina', 'Infraestructura', 'Freidora operativa', 3, false, false],
  ['Cocina', 'Infraestructura', 'Utensilios exigidos disponibles', 2, false, false],
  ['Cocina', 'Infraestructura', 'Toppineras en correcto estado', 2, false, false],
  ['Cocina', 'Infraestructura', 'Tablas de corte de colores según insumos', 1, false, false],
  ['Cocina', 'Infraestructura', 'Cartelería de señalización presente', 2, false, false],
  ['Cocina', 'Infraestructura', 'Paredes, pisos y aberturas', 2, false, false],
  ['Cocina', 'Infraestructura', 'Tachos de basura con tapa y en condiciones', 1, false, false],
  ['Cocina', 'Infraestructura', 'Tostadora de pan en óptimas condiciones', 2, false, false],
  ['Cocina', 'Limpieza', 'Mesadas en óptimas condiciones de trabajo', 3, false, true],
  ['Cocina', 'Limpieza', 'Campana y filtros en condiciones', 3, false, false],
  ['Cocina', 'Limpieza', 'Equipos de frío', 3, false, true],
  ['Cocina', 'Limpieza', 'Vajilla, tuppers, toppineras, mamaderas', 3, false, false],
  ['Cocina', 'Limpieza', 'Área de lavado ordenada y en condiciones', 2, false, false],
  ['Cocina', 'Limpieza', 'Piso seco y libre de residuos', 3, false, false],
  ['Cocina', 'Limpieza', 'Feteadora', 2, false, false],
  ['Cocina', 'Limpieza', 'Plancha', 3, false, true],
  ['Cocina', 'Bromatología', 'Temperatura de heladeras y freezer', 3, false, true],
  ['Cocina', 'Bromatología', 'FIFO y rotulación de productos', 3, false, true],
  ['Cocina', 'Bromatología', 'Orden en heladera (crudos abajo, cocidos arriba)', 3, false, true],
  ['Cocina', 'Bromatología', 'Productos en mal estado o descomposición', 3, false, true],
  ['Cocina', 'Bromatología', 'Verduras sanitizadas y almacenadas correctamente', 3, false, false],
  ['Cocina', 'Bromatología', 'Productos por encima de 20cm del suelo', 2, false, false],
  ['Cocina', 'Bromatología', 'Elementos de limpieza separados de alimentos', 3, false, true],
  ['Cocina', 'Bromatología', 'Mamaderas limpias sin residuos', 2, false, false],
  ['Cocina', 'Bromatología', 'Control de contaminación cruzada entre utensilios', 3, false, false],
  ['Cocina', 'Bromatología', 'Campana encendida durante el servicio', 3, false, true],
  ['Cocina', 'Bromatología', 'La verdura del servicio está en óptimas condiciones', 3, false, true],
  ['Cocina', 'Bromatología', 'La carne está en condiciones', 3, true, true],
  ['Cocina', 'Bromatología', 'Los medallones de carne están correctamente almacenados', 3, false, false],
  ['Cocina', 'Bromatología', 'Fecha de elaboración/vencimiento de panes', 3, false, false],
  ['Cocina', 'Bromatología', 'Tuppers de queso cheddar', 2, false, false],
  ['Cocina', 'Atención / Operación', 'Corte y armado de hamburguesas según manual', 3, true, true],
  ['Cocina', 'Atención / Operación', 'Cofias con cabello recogido, presencia de accesorios, uniformes reglamentario y manicura en condiciones del personal de cocina', 3, false, true],
  ['Cocina', 'Atención / Operación', 'Correcta presentación del producto final', 3, false, true],
  ['Cocina', 'Marca', 'Después de las 20hs no hay carne molida sin smashear', 3, true, true],
  ['Cocina', 'Marca', 'Peso de medallón, panceta', 3, false, true],
  ['Cocina', 'Marca', 'Corte de rodajas de tomate, cebolla y de lechuga', 2, false, false],
  ['Cocina', 'Marca', 'Packaging adecuado', 3, false, true],
  ['Cocina', 'Marca', 'Se respetan las marcas de los insumos', 3, true, true],
  ['Cocina', 'Marca', 'Control visual de cocción (temperatura interna carne)', 3, false, true],
  ['Cocina', 'Marca', 'Planilla de mermas y de cambio de aceite completas', 1, false, false],
  ['Cocina', 'Marca', 'Personal con uniforme completo', 2, false, false],
  ['Depósito/Almacenamiento', 'Infraestructura', 'Estanterías limpias y en buen estado', 2, false, false],
  ['Depósito/Almacenamiento', 'Limpieza', 'Sin plagas o indicios', 3, true, true],
  ['Depósito/Almacenamiento', 'Bromatología', 'FIFO y rotulación de productos', 1, false, false],
  ['Depósito/Almacenamiento', 'Bromatología', 'Separación alimentos / químicos', 3, false, true],
  ['Depósito/Almacenamiento', 'Bromatología', 'Control de fecha de panes y secos', 3, false, false],
];

const UMBRALES_CRITICOS = [
  { tipo: 'SECTOR', sector: 'Cocina', porcentaje_minimo: 0.8 },
  { tipo: 'AREA', area: 'Bromatología', porcentaje_minimo: 0.9 },
  { tipo: 'AREA', area: 'Marca', porcentaje_minimo: 0.8 },
];

const SEMAFORO = [
  { rango_min: 0, rango_max: 49, color: '#DC2626', etiqueta: 'Rojo', orden: 1 },
  { rango_min: 50, rango_max: 59, color: '#EA580C', etiqueta: 'Naranja', orden: 2 },
  { rango_min: 60, rango_max: 79, color: '#CA8A04', etiqueta: 'Amarillo', orden: 3 },
  { rango_min: 80, rango_max: 94, color: '#16A34A', etiqueta: 'Verde', orden: 4 },
  { rango_min: 95, rango_max: 100, color: '#D4AF37', etiqueta: 'Dorado', orden: 5 },
];

module.exports = { SECTORES, AREAS, ITEMS, UMBRALES_CRITICOS, SEMAFORO };
